reference:
    ref: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta"
    STAR: "/projects/wp4/nobackup/workspace/jonas_test/STAR-Fusion/references/GRCh37_gencode_v19_CTAT_lib_Apr032020.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa.star.idx"
    picard_ref: "/projects/wp4/nobackup/workspace/jonas_test/STAR-Fusion/references/GRCh37_gencode_v19_CTAT_lib_Apr032020.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa"
    STAR_fusion: "/projects/wp4/nobackup/workspace/jonas_test/STAR-Fusion/references/GRCh37_gencode_v19_CTAT_lib_Apr032020.plug-n-play/ctat_genome_lib_build_dir"
    Fusion_catcher: "/data/ref_data/fusioncatcher/human_v98"
    Arriba_index: "/projects/wp4/nobackup/workspace/jonas_test/Arriba/references2/STAR_index_GRCh37_RefSeq_hg19"
    Arriba_ref: "/projects/wp4/nobackup/workspace/jonas_test/Arriba/references2/GRCh37.fa"
    Arriba_gtf: "/projects/wp4/nobackup/workspace/jonas_test/Arriba/references2/RefSeq_hg19.gtf"
    Arriba_blacklist: "/projects/wp4/nobackup/workspace/jonas_test/Arriba/references2/blacklist_hg19_hs37d5_GRCh37_v2.1.0.tsv"
    Arriba_refdir: "/projects/wp4/nobackup/workspace/jonas_test/Arriba/references2"

configfiles:
    multiqc: "DATA/multiqc_config.yaml"

bed:
    bedfile: "DATA/Twist_RNA_Large_Design_sorted_merged.annotated.bed"
    intervals: "DATA/Twist_RNA_Large_Design_sorted_merged.annotated.interval_list"
    exonbed: "DATA/Twist_RNA_Large_Design_sorted_merged.annotated.bed"
    fpkm: "DATA/hg19_RefSeq.bed"

singularity: #Can be a docker container as well. This is converted to a singularity on the fly
    # default: "docker://gmsuppsala/twist_rna:develop"
    default: "docker://gmsuppsala/somatic:develop"
    default_arriba: "docker://gmsuppsala/twist_rna_arriba:develop"
    default_starfusion: "docker://gmsuppsala/twist_rna_starfusion:develop"
    Fusion_catcher: "docker://olopadelab/fusioncatcher:latest"
    # default_fusioncatcher: "docker://gmsuppsala/twist_rna_fusioncatcher:develop"
    # cartool: "/projects/wp2/nobackup/Twist_Myeloid/Containers/CARTools-200206.simg"
    mosdepth: "/projects/wp4/nobackup/workspace/somatic_dev/singularity/mosdepth.0.2.4.simg"
